### ISSUE TITLE
almost perfect, still had black borders in "first scene" in a "cutscene"

### ISSUE THREAD

**Issue by JuergenStein** [Lyall/HogwartsLegacyFix#1]
Had black borders on first scene in a cutscene, but as soon the current cutscene switched to another camera the black borders were gone.
So i would say, it's "almost" perfect.

I am talking about the very first "castle cutscene" after the intro gameplay.

**Comment by Sylvanas-1977** [comment]
If actually checked both Linux and Windows 11 on Windows 11 it works better then on Linux it just works in some cases and not other cases not sure if i did something wrong or have old patch causing issues maybe have to look again to verify.
Anyway petting cats on Linux gives black bars but not on Windows 11, i think its user error in my case or just Linux will re apply the patch and check again.

**Comment by truduEprocEss** [comment]
> Had black borders on first scene in a cutscene, but as soon the current cutscene switched to another camera the black borders were gone. So i would say, it's "almost" perfect.
> 
> I am talking about the very first "castle cutscene" after the intro gameplay.

That's an FMV.

I'm really surprised people can't tell the difference between a pre-rendered video and in-game cutscene.

**Comment by Sylvanas-1977** [comment]
I thought so to but then i pet a cat and black bars wheren't there they are on Linux not sure if patch actually works at all on Linux via proton i guess i find out soon will test without patch and then with updated patch, might just be expecting to much.

**Comment by JuergenStein** [comment]
> > Had black borders on first scene in a cutscene, but as soon the current cutscene switched to another camera the black borders were gone. So i would say, it's "almost" perfect.
> > I am talking about the very first "castle cutscene" after the intro gameplay.
> 
> That's an FMV.
> 
> I'm really surprised people can't tell the difference between a pre-rendered video and in-game cutscene.

No need to be so mean.
It's not uncommon that games crop ultrawide pre-rendered cutscenes for whatever odd reason.
And my hope was this is the case in HL as well, if that's not the case then the issue is solved.

**Comment by Lyall** [comment]
It does sound as though you are hitting an FMV sequence, there's a couple during the first opening hours of the game. The FMVs will be presented in their native aspect ratio so you will be seeing black bars during them. The FMVs aren't cropped to vert- like a lot of other UE4 games fortunately. I take it other cutscenes are working okay with the fix? If so, let me know and we can close the issue.

**Comment by JuergenStein** [comment]
Yes, the realtime rendered cutscenes work fine so far.
Sad about the FMVs, they seem to be indeed only pre-rendered in 16:9.
Nothing we can do then obviously :)
