### ISSUE TITLE
Simply won't work

### ISSUE THREAD

**Issue by rafaelgsbr** [Lyall/HogwartsLegacyFix#10]
I don't know what's going on, but this changes nothing in my game. I don't believe I'm doing anything wrong, but the cutscenes still have black bars. Does the game language affect this mod? I'm playing in Portuguese. Or maybe there's some conflict with EMP.dll? Yes, I'm playing the cracked version.

**Comment by Lyall** [comment]
See issue #8. I won't be offering any help to get it running on a pirated game.
