### ISSUE TITLE
Game doesn't launch at all with the fix

### ISSUE THREAD

**Issue by lovemonkeyz** [Lyall/HogwartsLegacyFix#3]
Followed the instructions, but game doesn't start at all if I have the fix added to the game folder. No error messages, no event logs, the exe simply doesn't open. Tried launching it directly from the game folder, but no dice. Any idea how I can troubleshoot this? I really hate having boxes in my cutscenes :(

**Comment by munsuri** [comment]
First take a look at the log file the mod fix generates at C:\Program Files (x86)\Steam\steamapps\common\Hogwarts Legacy\Phoenix\Binaries\Win64\HogwartsLegacyFix.log

It could also be silently crashing... enable crash dump collection just in case. Also, take a look at https://github.com/ThirteenAG/Ultimate-ASI-Loader which is used to load the mod fix to generate the dump and/or log.

**Comment by lovemonkeyz** [comment]
Hi,
Unfortunately, no log file for the fix is generated, and no crashdumps from the DLL either :/

**Comment by Lyall** [comment]
Can you try running with a [different DLL name](https://github.com/ThirteenAG/Ultimate-ASI-Loader#description)? For instance you could try renaming `version.dll` to `d3d12.dll` and see if that lets the game start correctly.

**Comment by lovemonkeyz** [comment]
Renaming the dll seems to have done the trick! Thank you <3

**Comment by Lyall** [comment]
Awesome, I'll close the issue and add this bit of advice to the readme in case others run into the same issue.
