### ISSUE TITLE
Giant ring on screen when looking at sky

### ISSUE THREAD

**Issue by Benny-JG** [Lyall/HogwartsLegacyFix#4]
I haven't tested to see if this mod is causing this issue, but I'm hoping maybe there is a way this mod can fix this issue regardless. Please see the image I attached. I am using a 5120x1440 monitor, whenever I look at the sky I see this.
![lgid5kvi6jha1](https://user-images.githubusercontent.com/88231927/218284761-8ae0b126-cb7d-444b-91af-db970201a9db.jpg)

**Comment by Lyall** [comment]
First of all can you try with `[Fix Aspect Ratio]` set to `Enabled = false` in your `HogwartsLegacyFix.ini`? You can find it in `steamapps\common\Hogwarts Legacy\Phoenix\Binaries\Win64`.

I don't imagine it is the fix that's causing that issue, it's more likely to be a 32:9 specific bug. That said; you never know, if you can try with the fix disabled and let me know if that fixes it then I can look in to it further.

**Comment by Lyall** [comment]
I just noticed [this bit on the PCGW page for Hogwarts Legacy](https://www.pcgamingwiki.com/wiki/Hogwarts_Legacy#Field_of_view_.28FOV.29). 

![image](https://user-images.githubusercontent.com/695941/218320524-e1fd89c5-023a-46b1-9e8c-81efd4929abc.png)

Do you have your FOV set too high? This may be the source of your problem perhaps.

**Comment by Benny-JG** [comment]
Hi, I do have the Fov maximised. I will test everything you mentioned tonight and respond! Thanks. Didn’t mean to close the request just yet that was a misclick.

**Comment by Benny-JG** [comment]
Apologies in the delay, I can now confirm it is indeed the high fov. The worst news is that pretty much every fov setting that is still above 0 still shows the ring, it just recedes closer to the edge of the monitor.

Thanks for pointing that out.

**Comment by Lyall** [comment]
After talking with someone else that had the same issue I confirmed the same results, even in the vanilla unmodified game. It looks to be a known bug with higher FOV and can even manifest slightly at 21:9 with the FOV slider maxed. At this point it's probably best to just have it reported as a bug to WB Games and hope that it gets fixed. With the confirmation that it's a game bug and not do with the fix, I'll close the issue.
