### ISSUE TITLE
Possible incorrect directory structure

### ISSUE THREAD

**Issue by tddouglas** [Lyall/HogwartsLegacyFix#6]
The pillarbox fix isn't working for me currently on my 21:9 monitor (still getting 16:9 cutscenes). Could you clarify the expected directory structure? I extracted the zip in the common folder leading to the below directory structure:
`"C:\Program Files (x86)\Steam\steamapps\common\Hogwarts Legacy\HogwartsLegacyFix-1.0\HogwartsLegacyFix-1.0"` and then all the repo's contents. 

Is this correct? If so, are there any other debugging steps you recommend?

**Comment by Lyall** [comment]
That doesn't look like the correct structure to me. You want something like this:
```
steamapps/
├─ common/
│  ├─ Hogwarts Legacy/
│  │  ├─ Phoenix/
│  │  │  ├─ Binaries/
│  │  │  │  ├─ Win64/
│  │  │  │  │  ├─ HogwartsLegacyFix.asi
│  │  │  │  │  ├─ HogwartsLegacyFix.ini
│  │  │  │  │  ├─ version.dll
│  │  │  │  │  ├─ HogwartsLegacy.exe
```

Essentially just extract the contents of the release zip in to `steamapps\common\Hogwarts Legacy`. The release zip already has the folder structure of `Phoenix\Binaries\Win64` for ease of use.

**Comment by tddouglas** [comment]
Thanks Lyall! That resolved my issue. Didn't realize unzipping to a specific destination directory has a different behavior than simply unzipping the file in-place and moving the contents.
