### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by Elejido** [Lyall/HogwartsLegacyFix#8]
Hi, any chance to get a manual for the configuration file? 

did it how you described it but still pillarbox in the cutscenes.

best

**Comment by Lyall** [comment]
Does it generate a `HogwartsLegacy.log` file in `<gamedir>\Hogwarts Legacy\Phoenix\Binaries\Win64`? If so can you post that log? 

If it's not generating a log then it's probably not being loaded correctly. It could be that you put it in the wrong directory or that the ASI loader dll is not being injected.

**Comment by Elejido** [comment]
Yes you are right, its not logging and there is no file. but iam correctly in the directory. Can i inject the dll loade manually?

**Comment by Lyall** [comment]
Can you post a screenshot of your `<gamedir>\Hogwarts Legacy\Phoenix\Binaries\Win64` directory? I just want to make sure you have the fix extracted to the right place.

If it is in the correct place you could try renaming `version.dll` to `d3d12.dll` and see if the game detects that instead.

**Comment by Khikki** [comment]
Hello Lyall, 
I assume that this is due to the fact that a pirated version of the game is being used, I also encountered such a problem, I don’t think that this is a quick solution, since the catalog looks different.
```
│  ├─ Hogwarts Legacy/
│  │  ├─ Phoenix/
│  │  │  ├─ Binaries/
│  │  │  │  ├─ Win64/
│  │  │  │  │  ├─ EMP.dll
│  │  │  │  │  ├─ HogwartsLegacy.exe
│  │  │  │  │  ├─ libScePad.dll
```

**Comment by Khikki** [comment]
Does it make sense to create an issue and ask you for help with this version of the game? or is it pointless?

**Comment by derickso** [comment]
A similar issue occurs with Skyrim modding and multiple dlls. There is a PROXY_LIBRARY setting that it uses to daisy chain dlls, I don't know if it would be up to Empress to implement it for her EMP.dll, or this mod for its version.dll

**Comment by Lyall** [comment]
> A similar issue occurs with Skyrim modding and multiple dlls. There is a PROXY_LIBRARY setting that it uses to daisy chain dlls, I don't know if it would be up to Empress to implement it for her EMP.dll, or this mod for its version.dll

The fix is distributed with Ultimate ASI loader (named `version.dll`). You could try renaming `EMP.dll` to `EMP.asi` to have it be loaded through ASI loader. Alternatively try one of the many other dll proxy names that the ASI loader can use. As for the directory structure, if that is truly different in a cracked copy then you would have to rewrite part of the fix to accommodate that. 

Anyway, that's all I'm going to offer in terms of helping those who are using a pirated copy. I'll be closing this issue now.

**Comment by derickso** [comment]
FWIW, renaming version.dll to d3d11.dll appears to work

**Comment by RandomDude4** [comment]
Renaming to d3d11.dll also fixed my issues, I tried several other filenames and none worked until I tried this one.
