### ISSUE TITLE
Hi mate.

### ISSUE THREAD

**Issue by v2sCollections** [Lyall/HogwartsLegacyFix#9]
Hi mate how are you im the one that posted youre widescreen fix on nexus. I wanted to message to ask as a courtesy but i didnt know you could message on Github. I read the mit license i just thought it was ok. I didnt take no credit for it and shared the link to youre fix and youre name i just wanted to help people like me that needed it. regards v2

**Comment by Lyall** [comment]
Hey sorry for the late reply to this. It's all good, the message was sent in error.
